In [66]:
import numpy as np
import pandas as pd
import os

In [67]:
# get filepath 
relative_fp = os.path.realpath(os.getcwd())
data_fp = '\\Blackrock-Caltech Research\\PitchBook_Public_Company_Financials_2020_07_10_18_53_44.xlsx'
fp = relative_fp + data_fp

# load data
df = pd.read_excel(fp, skiprows=6)

In [68]:
# clean data 
df.drop(df.columns[[0, 1]], axis=1, inplace=True)
df.columns = df.loc[0,:].values
df = df.drop(0) # first row is column name
df = df.dropna(subset=['Company Name']) # drop NaNs

In [69]:
# drop non-public firms
print(str(['(' in i for i in df['Company Name']].count(False)), 
      'non-public firms in pitchbook data')
df = df[['(' in i for i in df['Company Name']]]

165 non-public firms in pitchbook data

In [70]:
# only want public firms from NYS, NAS, and ASE
markets_interested = ['NYS:', 'NAS:', 'ASE:']

# nice double list comprehension!!!
print(str([True in [market in firm_name for market in markets_interested] 
for firm_name in df['Company Name']].count(True)), 'number of valid firms')

df = df[[True in [market in firm_name for market in markets_interested] 
 for firm_name in df['Company Name']]]

2331 number of valid firms

In [71]:
df.head(3)

,Company Name,EV/EBITDA (FY),"EBITDA (Earnings Before Interest, Tax, Depreciation, & Amortization) (FY)","EBITDA (Earnings Before Interest, Tax, Depreciation, & Amortization) (TTM)",EBITDA % Growth (FY),Revenue % Growth (FY),EBT Margin (FQ),Net Income % Growth (TTM),EBIT % Growth (FY),"EBITDA % Growth, 5 Year CAGR (FY)",...,Latest Stock Analyst Note,Latest Cash Flow Model,Morningstar Rating,Active Coverage,SIC Codes,SIC Code Descriptions,SIC Group Descriptions,SIC Sector Descriptions,Website,As of Date
1,Apple (NAS: AAPL),13.39,76899000,77633000,-5.48,-2.04,22.52,0.08,-8.66,5.08,...,subscribe,subscribe,subscribe,subscribe,3571,Electronic computers,Machinery & Computer Equipment,Manufacturing,www.apple.com,2020-07-10 00:00:00
2,Microsoft (NAS: MSFT),17.47,58056000,67000000,17.36,14.03,36.67,32.47,18.28,11.54,...,subscribe,subscribe,subscribe,subscribe,"3661, 7372","Services-prepackaged software, Telephone & tel...","Business Services, Electronic & Other Electric...","Manufacturing, Services",www.microsoft.com,2020-07-10 00:00:00
3,Amazon.com (NAS: AMZN),27.49,36533000,36038000,32.47,20.45,4.48,-12.02,20.48,50.03,...,subscribe,subscribe,subscribe,subscribe,"4731, 5942, 5961, 8742",Arrangement of transportation of freight & car...,"Engineering, Accounting, Research & Management...","Retail Trade, Retail Trade, Services, Transpor...",www.amazon.com,2020-07-10 00:00:00

In [72]:
sectors = df['Primary Industry Sector'].unique()
sectors = sectors[:-1]

In [73]:
sectors

array(['Information Technology', 'Consumer Products and Services (B2C)',
       'Healthcare', 'Energy', 'Financial Services',
       'Materials and Resources', 'Business Products and Services (B2B)'],
      dtype=object)

In [89]:
selected_companies = pd.DataFrame(columns = sectors)
n = 5
for sector in sectors:
    companies_of_sector = df[df['Primary Industry Sector'] == sector]['Company Name'].values
    #get n firms randomly
    companies_selected = companies_of_sector[np.random.choice(len(companies_of_sector), size=n, replace=False)]
    #update
    selected_companies[sector] = companies_selected

selected_companies

,Information Technology,Consumer Products and Services (B2C),Healthcare,Energy,Financial Services,Materials and Resources,Business Products and Services (B2B)
0,Qumu (NAS: QUMU),XpresSpa Group (NAS: XSPA),Molina Healthcare (NYS: MOH),Natural Resource Partners (NYS: NRP),Envestnet (NYS: ENV),Celanese (NYS: CE),Wrap Technologies (NAS: WRTC)
1,Micronet Enertec Technologies (NAS: MICT),Winnebago Industries (NYS: WGO),Capital Senior Living (NYS: CSU),FTS International Services (ASE: FTSI),Legacy Housing Corp (NAS: LEGH),Compass Minerals (NYS: CMP),Red Violet (NAS: RDVT)
2,Activision Blizzard (NAS: ATVI),Heska (NAS: HSKA),Akebia Therapeutics (NAS: AKBA),ChampionX (NYS: CHX),Permian Basin Royalty Trust (NYS: PBT),Hawkins (NAS: HWKN),Meritage Homes (NYS: MTH)
3,Elasticsearch (NYS: ESTC),Turning Point Brands (NYS: TPB),Select Medical Holdings (NYS: SEM),Hess (NYS: HES),Marine Petroleum Trust (NAS: MARPS),Hycroft Mining (NAS: HYMC),Cavco Industries (NAS: CVCO)
4,Aviat Networks (NAS: AVNW),Century Casinos (NAS: CNTY),Blueprint Medicines (NAS: BPMC),Schlumberger (NYS: SLB),North European Oil Royalty Trust (NYS: NRT),Pacific Ethanol (NAS: PEIX),Lakeland Industries (NAS: LAKE)

In [91]:
selected_companies.to_csv('randomly_selected_firms')